Fix classloading error in host identifier (#9931)
* #9784 avoid NoClassDefFoundError if host resolving failed

just retry it when it's asked next time.

* #9784 catch Errors too

Unfortunately, I don't know what error happened there, but I guess we also need to catch it.

* log the error when resolving host name/address

* #9784 log InterruptedException

I think this really happens sometimes, and causes NoClassDefFoundError in WebDriverException.

Fixes #9784